.editorconfig, .gitignore, Jenkinsfile, ubuntu-18-agent.json, validate-vars.json
I ran it with:
```json
{
"location": "pick one",
"resource_group_name": "****",
"subscription_id": "***",
"client_id": "***",
"client_secret": "***"
}
```
```shell
packer build --var-file vars.json ubuntu-18-agent.json
```
and then tested with:
```
az vm create     --resource-group ****    --name ****     --image **** --admin-username azureuser --ssh-key-values *****
```
=> Add ubuntu 18 agent

ubuntu-18-agent.json
=> Symbolic link agent-workspace m2 cache to home

Jenkinsfile
This allows specifying the locations for the images
=> Setup configs for image locations

Jenkinsfile, windows-2019-agent.json, windows-2019-docker-agent.json, windows-2019-provision.ps1
Added git-lfs to the Windows image and added a Windows docker image.
=> Add git-lfs to Windows image and a Windows docker image

windows-2019-provision.ps1
The path for java was not being setup correct.
=> Fix path for java

aws/ubuntu-18-agent.amd64.json, aws/ubuntu-18-agent.arm64.json, scripts/ubuntu-18-provision.aws.amd64.sh, scripts/ubuntu-18-provision.aws.arm64.sh
Currenlty arm64 AMI do not work because the script only works for amd64
=> Use different script for aws arm64 and aws amd64

aws/ubuntu-18-agent.amd64.json, aws/ubuntu-18-agent.arm64.json
https://issues.jenkins-ci.org/browse/INFRA-2543
=> [INFRA-2543] Increase ubuntu root disk size

aws/windows-2019-agent.amd64.json, scripts/windows-2019-provision.ps1
This uses existing Amazon powershell scripts to
complete the provisioning process. This sets up the
password setup.
=> Use existing Amazon powershell scripts

Jenkinsfile, aws/windows-2019-agent.amd64.json, build.sh, scripts/windows-2019-provision.ps1
Adds the public key from the credential into the image in the authorized_keys file
=> Add public key to packer images

Jenkinsfile, azure/windows-10-agent.amd64.json
This could be used for testing for the Windows Support Policy.
=> Add windows-10 agent for Azure

scripts/ubuntu-18-provision.sh
Intent described in https://issues.jenkins.io/browse/INFRA-2975
This PR introduces the following changes : 
add git and jq on the list of requirements packages
=> [INFRA-2975] Missing tools in agent images

.auto.pkrvars.hcl
Ref. https://github.com/jenkinsci/plugin-pom/pull/419#discussion_r648211794
=> Update Maven to 3.8.1

scripts/ubuntu-18-provision.sh
=> feat: remove Ubuntu APT Unattended Upgrades - INFRA-2956

scripts/ubuntu-18-provision.sh
See https://github.com/jenkinsci/docker/pull/1128#issuecomment-868803506
=> Install parallel on ubuntu

.auto.pkrvars.hcl, scripts/ubuntu-20-provision.sh, scripts/windows-2019-provision.ps1
=> Use Adoptium JDK 8u302-b08 and JDK11 11.0.12+7 [INFRA-3048]

jenkins-agent.pkr.hcl
=> hotfix: correct packer syntax to handle default_jdk variable

CiPodTemplate.yaml, Jenkinsfile_k8s, updatecli/updatecli.d/ciPodTemplate.yml, updatecli/updatecli.d/compose.yml, updatecli/updatecli.d/git-lfs.yml, updatecli/updatecli.d/git.yml, updatecli/updatecli.d/jdk11.yml, updatecli/updatecli.d/jdk17.yml, updatecli/updatecli.d/jdk8.yml, updatecli/updatecli.d/maven.yml
- Move to single JNLP container pattern to avoid Jenkins Kubernetes websockets timeouts
- Remove updatecli deprecated directives (0.17.x)
=> fix: correct builds

jenkins-agent.pkr.hcl, scripts/ubuntu-20-provision.sh
Docker official installation process as changed, this PR is implementing this : https://docs.docker.com/engine/install/ubuntu/
=> Update script install docker on linux

Jenkinsfile_k8s, run-packer.sh
just move fmt from packer file to script.
=> moving packer fmt -recursive

scripts/ubuntu-20-provision.sh
following #172 I am removing curl as it's not needed anymore.
=> Remove curl from ubuntu-20-provision.sh

scripts/ubuntu-20-provision.sh
Reverts jenkins-infra/packer-images#173
=> Revert "Remove curl from ubuntu-20-provision.sh"

scripts/ubuntu-20-provision.sh, scripts/windows-2019-provision.ps1
=> fix(JDK17) update provisionning URL to new patterns from adoptium

cleanup/azure.sh
=> chore: wrong wording

Jenkinsfile_k8s, cleanup/aws_images.sh
as per https://github.com/jenkins-infra/ideas/issues/36
remove the OLD AWS AMI marked as dev (more than 1 month old).
to be continued with : 
but need more input as for the filtering
=> feat(GC AWS AMI): Garbage collector for DEV images

updatecli/updatecli.d/azure-cli.yml, updatecli/updatecli.d/git-windows.yml, updatecli/updatecli.d/jdk11.yml, updatecli/updatecli.d/jdk17.yml, updatecli/updatecli.d/jdk8.yml, updatecli/updatecli.d/jq.yml, updatecli/updatecli.d/maven.yml
=> chore(updatecli) update manifests for 0.25.0

Jenkinsfile_k8s, updatecli/updatecli.d/maven.yml
Related:
- https://github.com/jenkins-infra/docker-inbound-agents/pull/29
- https://github.com/jenkins-infra/jenkins-infra/pull/2220
Supersede and closes https://github.com/jenkins-infra/packer-images/pull/256
=> feat: make packer-images the source of truth for Maven version

Jenkinsfile_k8s
Closes #284
Let's see if retried builds are timed out before increasing [its default value](https://github.com/jenkins-infra/packer-images/blob/main/Jenkinsfile_k8s#L24).
=> chore: add a retry on the pipeline

provisioning/windows-provision.ps1
Needed for `parcel` (npm tool)
Ref: https://github.com/jenkins-infra/helpdesk/issues/3105
=> feat: add Microsoft Visual C++ 2015 Redistributable to the Windows template

provisioning/ubuntu-provision.sh
to avoid bad logs before cloud-init generation of datadog.yaml
=> fix(datadog): disabling datadog at startup

provisioning/ubuntu-provision.sh
Ref. https://github.com/jenkins-infra/helpdesk/issues/3133
=> fix(ubuntu) ensure that ssh-agent and ssh client commands are installed in container images

provisioning/tools-versions.yml, provisioning/ubuntu-provision.sh, provisioning/windows-provision.ps1
Required for https://github.com/jenkins-infra/account-app/pull/167
see comments in code for some of the choices.
Unsure if it's worth adding to Windows, would rather not add it if it would never be used there
=> Add chromium version 105.0.5195.102

provisioning/tools-versions.yml, provisioning/ubuntu-provision.sh, provisioning/windows-provision.ps1
Ref. https://github.com/jenkins-infra/packer-images/issues/198
This PR does NOT have an updatecli tracking for the CLI (subsequent PR to avoid build failures)
=> feat: add awscli v2.8.9

updatecli/updatecli.d/jdk11.yml, updatecli/updatecli.d/jdk17.yml, updatecli/updatecli.d/jdk19.yml, updatecli/updatecli.d/jdk8.yml
goss need to follow the update in jdk version.
related to : 
- #480
- #482 
- #483
=> chore(updatecli): fix JDK manifest to update goss

Jenkinsfile_k8s
Ref. #477 
as deploy is outside the closure withPackerNode() the arm image is never published.
=> chore(Jenkinsfile): ensure that Docker ARM64 Linux are published

Jenkinsfile_k8s
And abort previous running builds.
=> chore: disable concurrent builds on pull requests

Jenkinsfile_k8s, build-jenkins-agent-ubuntu.pkr.hcl, locals.pkr.hcl, sources.pkr.hcl
as per https://github.com/jenkins-infra/helpdesk/issues/3471 and following #575
enable ubuntu 22.04 ARM on azure but exclude windows build in arm
=> feat(azure/arm): enable arm64 azure build

Jenkinsfile_k8s, build-jenkins-agent-ubuntu.pkr.hcl, locals.pkr.hcl, sources.pkr.hcl
Reverts jenkins-infra/packer-images#607
=> Revert "Revert "feat(azure/arm): enable arm64 azure build"" (#608

updatecli/updatecli.d/python3.yml
Closes https://github.com/jenkins-infra/packer-images/pull/611
Fixup of #605
=> chore(updatecli) fix python manifest

provisioning/ubuntu-provision.sh
Resolves https://github.com/jenkins-infra/packer-images/issues/535
=> chore: install `azure-cli` via deb package instead of `python3-dev`

updatecli/updatecli.d/jdk21.yml
as per https://github.com/jenkins-infra/helpdesk/issues/3736#issuecomment-1715131128
=> chore(updatecli): new manifest for jdk21

updatecli/updatecli.d/goss.yml
=> chore(updatecli): add a manifest to track goss

goss/goss.yaml
=> chore(ubuntu): rework of the goss file

provisioning/tools-versions.yml, provisioning/ubuntu-provision.sh, provisioning/windows-provision.ps1
Related to https://github.com/jenkins-infra/helpdesk/issues/3753
=> cleanup: remove tfsec

build-jenkins-agent-ubuntu.pkr.hcl, goss/goss.yaml, provisioning/ubuntu-provision.sh, updatecli/updatecli.d/asdf.yml
this change the way we perform GOSS check by impersonating the jenkins user
=> tests: check for `asdf` and `npm` with goss

provisioning/tools-versions.yml
Reverts https://github.com/jenkins-infra/packer-images/pull/862 and https://github.com/jenkins-infra/packer-images/pull/867
Ref. jenkins-infra/jenkins-infra#3126
=> hotfix(linux) revert remoting to `3174.v2c9e67f8f9df `

build-jenkins-agent-ubuntu.pkr.hcl, goss/goss-linux.yaml, provisioning/ubuntu-provision.sh
as per https://github.com/jenkins-infra/helpdesk/issues/3763#issuecomment-1812019058
phase 2 of migration within goss
=> chore(goss): moving all sanity checks to goss

goss/goss-linux.yaml
as per https://github.com/jenkins-infra/packer-images/pull/910 need to update goss-linux file in a separate PR for updatecli
from https://github.com/jenkins-infra/helpdesk/issues/3763
=> chore(goss): update goss-linux before updatecli

build-jenkins-agent-windows.pkr.hcl, goss/goss-windows.yaml, provisioning/windows-provision.ps1
first step move windows sanity checks to goss
=> chore(goss): move windows sanity checks from provider script to goss

provisioning/tools-versions.yml, provisioning/ubuntu-provision.sh
=> feat(doctl): add doctl install on linux only

goss/goss-linux.yaml, updatecli/updatecli.d/doctl.yaml
=> chore(updatecli/goss): include `doctl`

goss/goss-windows.yaml, provisioning/windows-provision.ps1, updatecli/updatecli.d/awscli.yml, updatecli/updatecli.d/azure-cli.yml, updatecli/updatecli.d/chocolatey.yml, updatecli/updatecli.d/container-structure-test.yml, updatecli/updatecli.d/docker-ce.yaml, updatecli/updatecli.d/docker-compose.yml, updatecli/updatecli.d/git-lfs.yml, updatecli/updatecli.d/github-cli.yml, updatecli/updatecli.d/goss.yml, updatecli/updatecli.d/hadolint.yml, updatecli/updatecli.d/jq.yml.disabled, updatecli/updatecli.d/launchable.yml, updatecli/updatecli.d/nodejs.yml, updatecli/updatecli.d/packer.yml, updatecli/updatecli.d/pwsh.yml, updatecli/updatecli.d/python3.yml, updatecli/updatecli.d/terraform.yml, updatecli/updatecli.d/updatecli.yml, updatecli/updatecli.d/vagrant.yml, updatecli/updatecli.d/yq.yml
=> chore(updatecli): add goss-windows as target

goss/goss-linux.yaml, provisioning/tools-versions.yml, provisioning/ubuntu-provision.sh
=> feat(xq) adding xq as new tool

goss/goss-linux.yaml, provisioning/tools-versions.yml, provisioning/ubuntu-provision.sh
=> feat: add tools (helm, helmfile, helmplugins, sops)

updatecli/updatecli.d/helm.yml, updatecli/updatecli.d/helm_diff.yml, updatecli/updatecli.d/helm_git.yml, updatecli/updatecli.d/helm_secrets.yml, updatecli/updatecli.d/helmfile.yml, updatecli/updatecli.d/sops.yml
adding the updatecli manifest corresponding to #961
=> chore(updatecli): add manifest for helm/helmfile/helmplugins/sops

goss/goss-linux.yaml, provisioning/ubuntu-provision.sh
as per https://github.com/jenkins-infra/packer-images/issues/198#issue-1187626132
=> feat(linux): add yamllint tool

build-jenkins-agent-ubuntu.pkr.hcl, build-jenkins-agent-windows.pkr.hcl, goss/goss-common.yaml, goss/goss-linux.yaml, goss/goss-windows.yaml
=> chore(goss): split linux and windows common goss tests to a common file

goss/goss-common.yaml, provisioning/ubuntu-provision.sh, sources.pkr.hcl
as per https://github.com/jenkins-infra/helpdesk/issues/3823#issuecomment-1908570581
correct path in order to use nodejs/npm or bundle as in https://github.com/jenkins-infra/infra-reports/blob/3076337651c78c2ecc40155f3856534fbfbbc5b5/fork-report/Jenkinsfile#L28:
=> feat(node): change npm version check and add asdf to path

goss/goss-common.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/3823#issuecomment-1908570581
and after this https://github.com/goss-org/goss/issues/872
=> chore(goss) enforce goss check for NPM and NODEJS

goss/goss-common.yaml, goss/goss-linux.yaml
as per https://github.com/jenkins-infra/packer-images/pull/1063#pullrequestreview-1942697264
=> chore(goss): remove CST from goss linus as already in common

provisioning/windows-provision.ps1
as per https://github.com/jenkins-infra/packer-images/pull/1090#pullrequestreview-1942705964
=> chore(windows): change installation from chocolatey to github binary for `yq`

Jenkinsfile_updatecli
PR done in pair with @dduportal to accelerate main branch builds.
=> chore(pipeline): diff only on non main branch for updatecli

Jenkinsfile_k8s, build-jenkins-agent-ubuntu.pkr.hcl, build-jenkins-agent-windows.pkr.hcl, locals.pkr.hcl
to avoid https://github.com/jenkins-infra/helpdesk/issues/4334 openssh not starting, we pin windows versions and check that upgrade doesn't crash
=> fix(windows): pin windows image version

Jenkinsfile_updatecli
As per https://github.com/jenkins-infra/helpdesk/issues/4365#issue-2610776824:
This PR integrates updatecli aws credentials once created.
=> chore(jenkinsfile):Add updatecli-aws-credentials

cleanup/aws.sh
As per https://github.com/jenkins-infra/helpdesk/issues/4355#issuecomment-2488415877
We enable debugging for the `aws.sh` script to fix the unexpected behaviour on infra.ci controller
=> hotfix(aws-garbage-collector) enables debugging for `aws.sh` script

cleanup/azure.sh
not needed anymore following #1596
=> chore(GC/azure) remove debug

provisioning/tools-versions.yml, tests/goss-linux.yaml
Reverts jenkins-infra/packer-images#1701
I did merge enthusiastically but it breaks the build.
=> Revert "Bump ASDF version to 0.16.0"

updatecli/updatecli.d/kubectl.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4258
=> chore(updatecli/kubectl) switch to 1.30 kubectl cli version

build-jenkins-agent-windows.pkr.hcl, provisioning/windows-provision.ps1
as per https://github.com/jenkins-infra/helpdesk/issues/4574
setting the right value within the registry
=> feat(windows): enable LongPaths in registry

updatecli/updatecli.d/golangci-lint.yml
fixup of #1923
Ref. https://github.com/jenkins-infra/packer-images/pull/1924#issuecomment-2875175921
=> chore(updatecli) fix golangci-lint manifest

provisioning/tools-versions.yml, provisioning/ubuntu-provision.sh, tests/goss-linux.yaml
as per https://github.com/jenkins-infra/helpdesk/issues/4687#issue-3130782264
adding typos to the allinone
=> feat(linux) add typos-cli
