jenkins-infra/packer-images

Jenkinsfile

Packer 1.5.2 includes several changes and bug fixes for Azure.
See release notes:
https://github.com/hashicorp/packer/blob/v1.5.4/CHANGELOG.md

Use packer 1.5.4 - latest release

---

ubuntu-18-agent.json

Jobs are failing on ci.jenkins.io (like the [archetype job](https://ci.jenkins.io/job/Tools/job/archetypes/job/master/)) because of an inconsistency between the docker-compose version installed from Ubuntu default repositories and the docker version installed by following the instructions at docker.com.  See https://github.com/docker/compose/issues/6023 for details
Use docker.com instructions to install both docker and docker-compose.

Install docker-compose per docker.com instructions

---

aws/ubuntu-18-agent.amd64.json
aws/ubuntu-18-agent.arm64.json
aws/windows-2019-agent.amd64.json
aws/windows-2019-docker-agent.amd64.json

If the name is not unique, each time we generate a new AMI, a new ID is assigned to the AMI name, and the previous image is not available anymore

Update AMI name to be unique

---

aws/windows-2019-agent.amd64.json

This updates the image to Windows Server 2004. This should allow us to build newer Docker images.

Update release of Windows Server 2019

---

aws/windows-2019-agent.amd64.json

Reverts jenkins-infra/packer-images#48
AMI doesn't contain docker/container support

revert: increase disk size for AWS Windows builder

---

aws/ubuntu-18-agent.amd64.json
aws/ubuntu-18-agent.arm64.json
aws/windows-2019-agent.amd64.json
azure/ubuntu-18-agent.amd64.json
azure/windows-2019-agent.amd64.json
build.sh
validate-vars.json

the idea of this PR is to make it easier to control the versions
of everything in a single place.

chore: move all version properties to build.sh

---

CiPodTemplate.yaml
Jenkinsfile
cleanup/aws.sh

This PR introduces the following changes:
- Add a cleanup task, executed at the end of the build. This task is executed in "dry run" all the time, and "for real" on the principal branch. There are 2 types of cleaned resources for now: instances and security groups.
- Fixes Pipeline to support the principal branch name change to `main`
- Switch Pipeline execution to Kubernetes Agent instead of Docker container in EC2 VMs (faster and cheaper)

Chore: add a daily cloud cleanup task [INFRA-2958]

---

scripts/ubuntu-18-provision.sh

The goal is to avoid `/home/jenkins/.m2` to a symlink
to a root-owned repository.
BREAKING CHANGE: `/home/jenkins/.m2` is not created and isn't a symlink anymore

feat: remove creation of custom directory in `/mnt/`

---

azure/agent.pkr.hcl

by using retries and async resource deletion to avoid blocking image.
Please note that these changes are only for Windows Server 2019 builds, on Azure.

chore: improve resiliency of the azure builds 

---

Jenkinsfile
jenkins-agent.pkr.hcl
run-packer.sh

This PR introduces semantic versioning of the images:
* Azure Shared Gallery is now fed the semantic version
* The images (on both Amazon and Azure) all have a tag `version` set to the version's value, to help tracking and cleaning up
The `jx-release-version` command line is used: please note that there is a custom pipeline shell step to gather the requirements. This steps might be replaced later by a custom image.
* `curl` and `git` are installed
* `git` is used to fetch tags (as the job configuration, right now, does not)
* `curl` is used to retrieve `jx-release-version` latest command
The scope of this PR is NOT about automatic tagging/release: this is the work of the next one :)

feat: define a semantic version from git tags

---

scripts/ubuntu-18-provision.sh

This PR fixes the error `dpkg: error processing archive /tmp/git-lfs_2.13.3_amd64.deb (--install):==> amazon-ebs.ubuntu-18: package architecture (amd64) does not match system (arm64)` caused by #70

fix: specify the correct architecture for git-lfs package in ubuntu

---

.auto.pkrvars.hcl
scripts/ubuntu-20-provision.sh

This PR bumps git to the version `2.33.0` to fix the failing builds on the principal branch.
It also includes the following changes:
- Never fails some operation in the Ubuntu 20.04 script (to ensure it can be tested in an idempotent way, preparing for future Docker images)
- Provides a better output when a package is not found in the expected version (such as `git 2.32.0` for instance...)

Bump git to 2.33.0

---

scripts/ubuntu-20-provision.sh

- Automatically define Ubuntu's code name when needed
- Keep using `apt-get` instead of `apt` (because unstable CLI API)
- Add CLI requirements check as first step to ensure early failure
This PR is a set of non functionnal improvements made along the recent changes here. It also sets the grounds for futur "Docker" images.

chore: improve ubuntu provisioning script for sustainability

---

scripts/ubuntu-20-provision.sh

Java 11 reports a [null pointer exception](https://ci.jenkins.io/job/Plugins/job/git-plugin/job/master/lastCompletedBuild/testReport/hudson.plugins.git/GitSCMTest/linux_8___Build__linux_8____testConfigRoundtrip/) running JenkinsRule tests if the fontconfig package is not available.  Package is included in the Docker agent images also.

chore: Add fontconfig to Ubuntu image

---

Jenkinsfile_k8s
jenkins-agent.pkr.hcl
scripts/windows-2019-provision.ps1

This PR introduces the following fixes to the windows builds and provisioning:
- Increase instance size to have enough I/O and network
- Add multiples instances of `windows-updates` as per https://github.com/rgl/packer-plugin-windows-update/issues/90#issuecomment-842276886 (tip from the author of the packer plugin to handle all windows updates edge cases)
- implies using the provisioner's attribute `pause_before`
- Improve download performances on powershell script by disabling the progress bar (the gain is impressive: from 6m to 40s for downloading JDK11 for instance)
- Stop waiting for sys prep to reach a certain state: sometimes it's never reached until the VM is restarted, and there are no impacts in an environment such as this one (issue with the build stuck on loop with the message …

fix: Windows builds speed + sysprep

---

Jenkinsfile_k8s
updatecli/scripts/check-maven.sh
updatecli/updatecli.d/maven.yml

This Pull Request should close #98 , that was opened by the bot, from the updatecli manifest for Maven: the Maven tag 3.8.3 has been published but the binary is not generally available.
A condition had been added to the updatecli's maven manifest, so no PR will be opened if the binary is not available.

chore [updatecli] fail automatic update of maven if there are no binary available

---

jenkins-agent.pkr.hcl

to allow using instances which local ephemeral disks are limited to 100 Gb
Ref. https://github.com/jenkins-infra/jenkins-infra/pull/1897

feat: decrease os disk size to 90 Gb 

---

updatecli/updatecli.d/git-lfs.yml

This PR closes #99 by only checking for 2.x versions of git-lfs.

chore [updatecli] pin git-lfs to major version 2.x.y

---

jenkins-agent.pkr.hcl

This PR uses the "smalldisk" version of Windows server Core 2019 with Container generation 2 (yes that is a loooong name).
This base OS features a system drive at 30 Gb instead of 127 Gb, leaving us a lot of room for builds (~75 Gb), but staying below the limit of 100 Gb disks.

fix [azure windows-2019] use smaller base OS image to allow OS disk <100Gb

---

scripts/ubuntu-20-provision.sh
scripts/windows-2019-provision.ps1

This PR defines static installation paths for the JDK installation, which only depends on the java major version, to avoid the maintenance burden.
Ref. https://github.com/jenkins-infra/pipeline-library/issues/228#issuecomment-930219117.
The new paths are:
- Ubuntu Linux 20.04: 
```shell
/opt/jdk-8
/opt/jdk-11
/opt/jdk-17
```
- Windows 2019:
```powershell
C:\Tools\jdk-8
C:\Tools\jdk-11
C:\Tools\jdk-17
```

Feat: Define a common paths for JDKs, only based upon major versions

---

Jenkinsfile_k8s

chore(Jenkinsfile) the jx-release-version is not needed anymore

---

scripts/ubuntu-20-provision.sh

The `jenkinsci/packaging` repository accepts pull requests, but the `Jenkinsfile` does not run the tests in CI. As a result the packages are at high risk of regression (jenkinsci/packaging#235). To solve this problem, I have proposed jenkinsci/packaging#240 to add test coverage for the packages in the `Jenkinsfile`. That PR, on @dduportal's suggestion, runs this workload on the VM agents available on `ci.jenkins.io` by using the `docker` label.
The VM agents available on `ci.jenkins.io` lack the packages needed to run Python jobs, including Ansible/Molecule tests. I was able to work around this in jenkinsci/packaging#240 by adding the following shell script to my Jenkins job:
```shell
sudo apt-get update && sudo apt-get install -y python3-docker python3-pip python3-venv
```
However, this …

Install Python 3

---

.auto.pkrvars.hcl
scripts/ubuntu-20-provision.sh
updatecli/scripts/check-jdk.sh
updatecli/updatecli.d/jdk17.yml

Refines the updatecli definition to use the same pattern as is used for JDK 11.
Makes progress on jenkins-infra/helpdesk#2758

Use JDK 17.0.2, not 17.0

---

CiPodTemplate.yaml
Jenkinsfile_k8s
cleanup/azure.sh

Find every resources group that start with "pkr-Resource-" and is more than 1 day old from the tag timestamp and delete them as per the model for AWS : https://github.com/jenkins-infra/helpdesk/issues/2812
2 differences:  
-    no --dry-run in azure so I switch to the show sub-command to dry run
-    no batch delete command so I loop within the result list to delete one by one.   
PS : didn't add a location check as per : https://github.com/jenkins-infra/packer-images/blob/7a990b12227136625752012755dda690dc1475c2/jenkins-agent.pkr.hcl#L179 this seems to always be "eastus"

chore: GC for azure resources group from packer process

---

Jenkinsfile_k8s

Followup of https://github.com/jenkins-infra/packer-images/pull/185 to close https://github.com/jenkins-infra/packer-images/issues/183
Tested with a replay here: https://infra.ci.jenkins.io/blue/organizations/jenkins/packer-images/detail/main/106/pipeline/304

chore: use 1 azure credentials instead of 3 string credentials

---

Jenkinsfile_k8s

Closes #189 .
This PR switches from a github (personal) token usage to a githubapp => "Installation token usage".
Please note that the githubapp infra is used (instead of the updatecli githubapp) as packer init does NOT need any write access.

chore(Jenkinsfile) Use githubApp credentials for packer instead of a Github bot user token

---

.auto.pkrvars.hcl
scripts/windows-2019-provision.ps1

Reverts jenkins-infra/packer-images#192
Reason: https://github.com/jenkins-infra/helpdesk/issues/2835.

Revert Maven back to 3.8.4

---

.auto.pkrvars.hcl

https://github.blog/2022-04-12-git-security-vulnerability-announced/
CVE-2022-24765 - ceiling directory defense

Use git 2.35.2

---

scripts/ubuntu-20-provision.sh

Fix https://github.com/jenkins-infra/helpdesk/issues/2892

fix(ubuntu) ensure that Docker CE works by adding delay before loading the Docker GPG key to let enough time to the GPG agent to initialize

---

scripts/ubuntu-20-provision.sh

This PR follows up #211 , as it was auto-merged by error (the GH checks failed but allowed us to merge, it's fixed and should not happen anymore).
It introduces the following changes:
- Built on top of the following manually merged PRs: #208 #209 #213 (to ensure that we have last jenkins-agent, last packer version and last git package version so vuilds are not blocked, because older git version are not available anymore in the apt repo)
- Forces the GPG command to answer "yes" to all questions, which fixes the initial GPG problem.

fix(ubuntu) Ensure that Docker GPG key is loaded without error

---

scripts/windows-2019-provision.ps1

Ref: https://github.com/jenkins-infra/helpdesk/issues/2873
Follow-up of https://github.com/jenkins-infra/packer-images/pull/225
Instead of installing other GNU tools via Chocolatey in order to run [a common Makefile](https://github.com/jenkins-infra/pipeline-library/blob/master/resources/io/jenkins/infra/docker/Makefile) to build Docker images on every architecture, we can retrieve almost all needed GNU tools from those included with Git for Windows (notable exception, `make`):
I tried move all of them in C:\tools\ but then I retrieved empty responses from almost all common Windows or shell commands, probably due to conflicts between them, hence the cherry-picking.

feat: copy common GNU tools included with git for Windows in the $baseDir tool folder

---

build-jenkins-agent-ubuntu.pkr.hcl
build-jenkins-agent-windows.pkr.hcl
provisioning/windows-provision.ps1

This PR comes from https://github.com/jenkins-infra/helpdesk/issues/2942.
It changes the Azure SKU to a Windows Server 2019 without containers and takes care of installing Docker CE on any windows when it is not detected.

feat(Azure Windows) switch to Windows Server 2019 Core without containers

---

Jenkinsfile_k8s
build-jenkins-agent-windows.pkr.hcl
datasources.pkr.hcl

Related to https://github.com/jenkins-infra/helpdesk/issues/2629.
Depends on #221 and #239.
This PR introduces an additional set of VM templates with Windows Server Core 2022 as base OS.
Please note that:
- Docker container is excluded (for now): only AWS and Azure VM templates are added.
- Windows Server 2019 is kept (see comment below for details)

feat(windows) bump Windows Server to 2022 edition

---

provisioning/windows-provision.ps1

It seems there is a collision between them and the tools included with git for Windows when used in the buildDockerAndPublishImage shared pipeline lib:
> Cloning into 'private-repo'...
>       0 [main] cat (2272) C:\tools\git\usr\bin\cat.exe: *** fatal error - cygheap base mismatch detected - 0x180348408/0x18034C408.
> This problem is probably due to using incompatible versions of the cygwin DLL.
Related: https://github.com/jenkins-infra/helpdesk/issues/2873

fix: no cygwin

---

datasources.pkr.hcl

Ref. https://github.com/jenkins-infra/packer-images/issues/253
This PR is a hotfix to ensure that  we can keep building a valid Windows Server 2019 in AWS.
- Comment added in the packer file
- Since we are applying all available Windows updates, the resulting image will be fresh and up to date. Just longer to build.
- We might use updatecli on a subsequent PR that would extract the latest image and open PR, so we can test. For Windows Server on AWS, it's ~2 updates per month so it could be sustainable.

hotfix(windows-2019) pin to 2022 05 11 build on AWS 

---

datasources.pkr.hcl

Reverts jenkins-infra/packer-images#254
=> Closes #253
Pro of this revert: faster builds :)

Revert "hotfix(windows-2019) pin to 2022 05 11 build on AWS "

---

updatecli/updatecli.d/jenkins-remoting.yml

Remoting releases don't follow semver anymore: https://github.com/jenkinsci/remoting/releases

fix: remoting manifest

---

Jenkinsfile_k8s

Follow-up of https://github.com/jenkins-infra/packer-images/pull/287
Use correct credentials (needs https://github.com/jenkins-infra/kubernetes-management/pull/2644)
Set isPrimary variable as env.BRANCH_IS_PRIMARY doesn't seem to be available in scripted
Add a condition on compute_type for the 'publish docker image' stage
Ref: https://github.com/jenkins-infra/packer-images/issues/282

fix: release Docker image for Linux

---

updatecli/updatecli.d/vagrant.yml

chore(updatecli) fix vagrant manifest by adding a condition to check for chocolatey package to be published before opening a PR

---

Jenkinsfile_k8s
variables.pkr.hcl

Closes #279 which was an experiment in full scripted syntax for pipeline. This PR instead keeps the handy `matrix` syntax from declaratives and adds a bit of scripted to manage the "node" allocation.
The idea is to use the same VM agent with Docker for ALL packer builds, except the specifics (such as arm64 linux today, faster than using qemu for this, and windows container in the near future).

chore(Jenkins) use as less agent nodes as possible

---

provisioning/ubuntu-provision.sh
provisioning/windows-provision.ps1

Related to https://github.com/jenkins-infra/helpdesk/issues/2980, this PR add the latest datadog-agent available on both Ubuntu and Windows.
Please note that:
- Latest version is used (APT package on Ubuntu, Chocolatey package on Windows)
- The associated service is not started neither enabled: that would be the role of the system that will start instances (Jenkins EC2 plugin, Jenkins Azure VM plugin)

feat: add datadog-agent v7 (latest)

---

provisioning/ubuntu-provision.sh

Ref. https://github.com/jenkins-infra/helpdesk/issues/3124

fix(ubuntu) add azure-cli missing python dependencies (since v2.40)

---

sources.pkr.hcl

Ref. https://github.com/jenkins-infra/helpdesk/issues/3132
The associated UID is `1001`: https://github.com/jenkins-infra/packer-images/blob/main/provisioning/ubuntu-provision.sh#L14. it's the same as VMs, but is a change from previous container images.

fix(ubuntu - docker) set default user to "jenkins" (UID: 1001)

---

provisioning/tools-versions.yml
provisioning/ubuntu-provision.sh
provisioning/windows-provision.ps1

For https://github.com/jenkins-infra/packer-images/issues/198
This PR add tfsec on all platforms

feat: add tfsec (v1.28.1) on all platforms

---

provisioning/ubuntu-provision.sh

Related to https://github.com/jenkins-infra/helpdesk/issues/3400
Since [Docker 23.x](https://docs.docker.com/engine/release-notes/23.0/) line (that we added in https://github.com/jenkins-infra/packer-images/pull/500), the [Docker BuildX plugin](https://docs.docker.com/build/install-buildx/) does not seem to be part of the default `docker-ce-cli` package in Ubuntu, but it is now a separated package.
As we install with the `--no-install-recommends`, it led to buildx not being present since the [`0.58.0`](https://github.com/jenkins-infra/packer-images/releases/tag/0.58.0) release.
This PR fixes the problem by following the new Docker's documentation instructions (updated in https://github.com/docker/docs/commit/72d3016e81b93c4ce4e6c8e7b3400ac042d16a26) by adding the required package.
Tested …

fix(ubuntu) add `docker-buildx-plugin` package (orphaned from `docker-ce-cli` since Docker-CE 23.x)

---

build-jenkins-agent-windows.pkr.hcl

Using the "smalldisk" template, we were generating VMs with 30Go OS disk:
```
C:\Users\smallDiskUser>for /f "tokens=1-3" %a in ('WMIC LOGICALDISK GET FreeSpace^,Name^,Size ^|FINDSTR /I /V "Name"') do @echo wsh.echo "%b" ^& " free=" ^& FormatNumber^(cdbl^(%a^)/1024/1024/1024, 2^)^& " GiB"^& " size=" ^& FormatNumber^(cdbl^(%c^)/1024/1024/1024, 2^)^& " GiB" > %temp%\tmp.vbs & @if not "%c"=="" @echo( & @cscript //nologo %temp%\tmp.vbs & del %temp%\tmp.vbs
C: free=18.32 GiB size=29.45 GiB
D: free=14.07 GiB size=16.00 GiB
```
Tested on a VM manually spawned with `2019-datacenter-core-g2` as base template, we're getting a bigger OS disk:
```
C:\Users\noSmallDiskUser> for /f "tokens=1-3" %a in ('WMIC LOGICALDISK GET FreeSpace^,Name^,Size ^|FINDSTR /I /V "Name"') do @echo wsh.echo "%b" ^& " free=" …
```

fix: don't use small disks VM templates for Azure Windows templates

---

provisioning/ubuntu-provision.sh

While working on #299 , it appears that the list of packages changes over OS versions and playwright versions.
This PR ensured that we install the dependencies specified by the latest playwright version.
Note that it requires NPM to be up to date.

fix(ubuntu) ensure playwright dependencies are installed by playwright

---

Jenkinsfile_k8s
cleanup/aws_images.sh
cleanup/aws_snapshots.sh

Implements https://github.com/jenkins-infra/helpdesk/issues/2846#issuecomment-1120206965, in the context of https://github.com/jenkins-infra/helpdesk/issues/3502.
This PR add a GC for AWS snapshots, restricted to `us-east-2` .

chore(cleanup AWS) garbage collect EC2 snapshots older than 1 year on `us-east-2`

---

Jenkinsfile_k8s
cleanup/aws_images.sh

Implements the "Delete staging images older than 1 week" from https://github.com/jenkins-infra/helpdesk/issues/2846
This PR introduces 3 (linked) changes:
- Parameterized the `cleanup/aws_images.sh` script to allow passing parameters
- `$1` specifies the number of days for which the AMIs older than this threshold will be removed. Defaults to `1` (day).
- `$2` specifies the build_type for AMIs to check for deletion. Defaults to `dev`.
- Enable parallelization, like in #589 to ensure there are NO fail fast
- Enable cleanup of staging images older than 7 days

chore(cleanup AWS images) ensure staging images older than 7 days are removed

---

Jenkinsfile_k8s

Ref. https://github.com/jenkins-infra/helpdesk/issues/2846

chore(cleanup AWS images) remove AMI with build_type=prod older than 2 months

---

Jenkinsfile_k8s

Related to https://github.com/jenkins-infra/helpdesk/issues/3502
Since https://github.com/jenkins-infra/helpdesk/issues/3421, we have disabled the EC2 VM agents for Linux `x86` and Windows (all types).
Better to avoid wasting credits: this PR disable these build types.
Please note that it does NOT remove the underlying Packer configuration

cleanup: stop building EC2 Linux amd64 and EC2 Windows

---

cleanup/aws_snapshots.sh

Related to https://github.com/jenkins-infra/helpdesk/issues/2846 and https://github.com/jenkins-infra/helpdesk/issues/3502
Since the AMI for `build_type=dev` are cleaned up after 24h, we have to do the same for snapshots.
Some figures: With the 2 mointh threshold for snapshots, we still have ~1000 snapshots (that's a LOT of packer builds :D )

chore(cleanup AWS snapshots) try to delete when older than 1 day

---

build-jenkins-agent-ubuntu.pkr.hcl
build-jenkins-agent-windows.pkr.hcl
locals.pkr.hcl
sources.pkr.hcl

As per https://github.com/jenkins-infra/helpdesk/issues/3502 and https://github.com/jenkins-infra/helpdesk/issues/3485, cloud cost control is important for us.
The goal of this PR is to ensure that packer VM used to build VM templates are always using Spot prices on both AWS EC2 and Azure.

chore: ensure that spot instances are used for packer builds

---

Jenkinsfile_k8s
build-jenkins-agent-ubuntu.pkr.hcl
locals.pkr.hcl
sources.pkr.hcl

Reverts jenkins-infra/packer-images#600 until https://github.com/jenkins-infra/packer-images/issues/604 is ready as we currently need to manually delete dev/staging images before every build otherwise

Revert "feat(azure/arm): enable arm64 azure build"

---

cleanup/azure.sh

Follow up of #627 : this PR optimizes the Azure Gallery version deletion (as it works but takes more than 1 hour today, hitting the timeout).
Also fixes shellcheck issues (protip: when using shell, always use double quote)

chore(cleanup Azure) parallelize the Gallery version deletion and fix shellcheck issues

---

Jenkinsfile_k8s
cleanup/azure.sh

Related to https://github.com/jenkins-infra/helpdesk/issues/3552, this PR cleans up ALL resources older than the provided threshold in days for each of the 3 RGs (including VM, vaults, disks, public IP, NIC, etc.)
Please note I chose to call the script 3 times (each RG) with the same threshold. The goal is to surface, at pipeline level, the parameters (instead of hiding it inside the script). 
It has the benefit to make the script simpler, less loops, so the execution time and logs are easier to gather.

chore(azure cleanup) remove resources from the packer-builds RGs

---

Jenkinsfile_k8s

as per https://github.com/jenkins-infra/helpdesk/issues/3471

chore(pipeline) use ARM64 instead of x86_64 machine by default

---

updatecli/scripts/fetch-docker-ce-latest-version.sh

as per the error in the condition:
`23.0.6-1`
```
HTTP/2 404 
x-amz-error-code: NoSuchKey
x-amz-error-message: The specified key does not exist.
x-amz-error-detail-key: win/static/stable/x86_64/docker-23.0.6-1.zip
```

chore(updatecli): correct script for docker-ce to avoid -1 in version number

---

main.pkr.hcl

Since https://github.com/jenkins-infra/packer-images/pull/711, packer is using the 1.9.x line which throws the following error:
```
Error: Unsupported Packer Core version 
on main.pkr.hcl line 2, in packer:
2:   required_version = ">= 1.7.2, < 1.9.0"
```
We cannot use updatecli to automate this version constraint as packer version must be upgraded before trying to use it.

chore(packer) bump the maximum version to 1.9.x

---

provisioning/tools-versions.yml

Reverts jenkins-infra/packer-images#743 and downgrade launchable to the last known working version (1.66).
cc @basil

Revert "Bump launchable version to 1.67.1"

---

goss/goss.yaml
provisioning/tools-versions.yml
provisioning/ubuntu-provision.sh
provisioning/windows-provision.ps1

as per https://github.com/jenkins-infra/helpdesk/issues/3709

feat: add JDK21 version jdk21-2023-08-09-06-56-beta prerelease

---

provisioning/tools-versions.yml

as the old version break the builds on main (https://infra.ci.jenkins.io/blue/organizations/jenkins/infra-tools%2Fpacker-images/detail/main/809/pipeline/152#step-190-log-946) we need to bump the nodejs version.  manually for now but we need to updatecli it see : https://github.com/jenkins-infra/packer-images/issues/476#issuecomment-1702423195

Bump `nodejs` version to 18.17.0

---

provisioning/tools-versions.yml

Reverts jenkins-infra/packer-images#746 because launchable breaks builds: https://github.com/jenkins-infra/helpdesk/issues/3756

Revert "Bump launchable version to 1.75.0" (to version 1.66.0)

---

build-jenkins-agent-ubuntu.pkr.hcl
goss/goss.yaml
provisioning/tools-versions.yml
provisioning/ubuntu-provision.sh
provisioning/windows-provision.ps1
updatecli/updatecli.d/trivy.yaml

Ref. https://github.com/jenkins-infra/helpdesk/issues/3753
- Installed on both Linux arm64 + x86_64 (binary) and Windows (chocolatey)
- Tested with `goss` instead of the shell (to start migrating sanity checks to goss)
- Added an updatecli manifest to track its version (tested locally and works, but the checks will fail here)
- Note that goss is also updated by the manifest

feat: add trivy `0.45.1`

---

provisioning/ubuntu-provision.sh

The builds are failing since 24h due to the following error:
```
E: Version '2.53.0-1~jammy' for 'azure-cli' was not found
```
This PR ensures that we use a pattern to get the latest package increments

hotfix(ubuntu) correct azure-cli installation method to support package increments

---

updatecli/scripts/check-jdk.sh
updatecli/updatecli.d/jdk21.yml

as per https://github.com/jenkins-infra/helpdesk/issues/3783

chore(updatecli): track the official jdk21 version instead of earlyavailable

---

provisioning/tools-versions.yml

Reverts https://github.com/jenkins-infra/packer-images/pull/838 which failed with the following error:
```text
09:13:59  [0;32m2023-10-17T07:13:58Z:     azure-arm.windows: pwsh not installed. The package was not found with the source(s) listed.[0m
09:13:59  [0;32m2023-10-17T07:13:58Z:     azure-arm.windows:  Source(s): 'https://community.chocolatey.org/api/v2/'[0m
09:13:59  [0;32m2023-10-17T07:13:58Z:     azure-arm.windows:  NOTE: When you specify explicit sources, it overrides default sources.[0m
09:13:59  [0;32m2023-10-17T07:13:58Z:     azure-arm.windows: If the package version is a prerelease and you didn't specify `--pre`,[0m
09:13:59  [0;32m2023-10-17T07:13:58Z:     azure-arm.windows:  the package may not be found.[0m
09:13:59  [0;32m2023-10-17T07:13:58Z: …
```

fix(windows) bump pwsh back to `7.3.7`

---

goss/goss.yaml

Fixup of https://github.com/jenkins-infra/packer-images/pull/836
We started to check for the NPM version but it failed since a few days.
- Today: Goss checks that NPM version is `10.2.0` since https://github.com/jenkins-infra/packer-images/pull/836/files#diff-9857eb30c03fe9a9f3468d7e4674aa42c75beb888b63eab5615d67fb539147e4R36
- But: during the provisioning steps (before goss) we are upgrading NPM to the latest version available: https://github.com/jenkins-infra/packer-images/blob/e5f20e37b091b58af9068d6673da0eddf0ceb723/provisioning/ubuntu-provision.sh#L565
- Since 2 days, the latest version is different, making the goss check failing.
This PR proposes to, instead:
- Only check for NPM presence 
- But check the NodeJS installed version (as we specify it)
(edit) please note that this PR is …

tests: fix failing NPM check by replacing it with a NodeJS check instead

---

goss/goss.yaml
provisioning/tools-versions.yml
provisioning/ubuntu-provision.sh
provisioning/windows-provision.ps1

- Fixup of https://github.com/jenkins-infra/packer-images/pull/839 as the download URLs in the provisioning script were not upgraded
- Closes #848 (supersedes)
- Goss is also updated

feat: Bump JDK21 to Temurin 21+35 LTS version

---

provisioning/windows-provision.ps1
updatecli/updatecli.d/nodejs.yml

The goal of this PR is double:
- Same feature parity between Linux and Windows agents (NodeJS is worth installing on Windows for developers).
- Add a tracking of the (still) current LTS for NodeJS => this should propose an upgrade to latest 18.x with less download errors

feat: add NodeJS to windows and track its version

---

build-jenkins-agent-windows.pkr.hcl
goss/goss-windows.yaml
provisioning/windows-provision.ps1

Related to https://github.com/jenkins-infra/helpdesk/issues/3763
This PR introduces the following changes:
- Install `goss` on the Windows templates
- Introduces a `goss/goss-windows.yaml` test harness only for Windows which is deleted at the end (cc @smerle33 for info, we'll want to remove linux and common test harness when we will refactor)
- Add a "breakpoint" provisionner on Windows to allow local debug
- Move the sanity checks for all the JDK, trivy and default JDK
💡 Note: this PR does NOT add an updatecli manifest. We'll wait for the aforementioned refactor

tests(windows) Use `goss` for sanity checks for JDKs and trivy

---

build-jenkins-agent-ubuntu.pkr.hcl
goss/goss.yaml
provisioning/tools-versions.yml
provisioning/ubuntu-provision.sh
updatecli/updatecli.d/playwright.yml

Fixes #584 
Remove build artifacts accidentally introduced during `playwright`'s sanity check. The fix is backwards-compatible as it registers the installed `playwright`'s version somewhere before cleaning up all.

fix(provision): clean playwright artifacts during sanity check

---

updatecli/updatecli.d/jdk11.yml
updatecli/updatecli.d/jdk17.yml
updatecli/updatecli.d/jdk21.yml
updatecli/updatecli.d/jdk8.yml
updatecli/updatecli.d/playwright.yml
updatecli/updatecli.d/trivy.yaml

This PR is quick one I had in my staging area.
Closes #881 (which has its Goss test failing due to not checking the new version). A new JDK21 PR will be opened once merged here.
Closes #885 (missing `scmid` in the target preventing upgrade of goss harness).
Note: I also added a `PATH` for shell conditions when it failed to run on my machine while testing (to ensure any `asdf` or `homebrew` tools providing tools such as `jq` are being used).
Note 2: I've tested the 2 skipped manifests (trivy and JDK17) by changing the source to a kind `shell` printing the version currently in production instead of the detected one.

chore(updatecli) fix manifests when they need to updated both GOSS test harnesses

---

goss/goss-linux.yaml

This PR is a quick fixup of #835 
- (nit) sort execution targets
- (fix) call `node --version` for the NodeJS version check
- (fix) remove stdout assertions for tools which version is not pinned
- (feat) add a check for the default Java version

chore(tests) fix goss linux harness

---

goss/goss-linux.yaml
provisioning/tools-versions.yml
provisioning/ubuntu-provision.sh

This PR adds https://github.com/Azure/azure-storage-azcopy to Linux provisioning so we can use it in https://github.com/jenkins-infra/crawler/ job to synchronize the Update Center File Share that will be used by updates.jenkins.io.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/2649#issuecomment-1807816044

feat: add `azcopy` to Linux provisioning

---

updatecli/updatecli.d/asdf.yml
updatecli/updatecli.d/awscli.yml
updatecli/updatecli.d/azcopy.yaml
updatecli/updatecli.d/azure-cli.yml
updatecli/updatecli.d/compose.yml
updatecli/updatecli.d/container-structure-test.yml
updatecli/updatecli.d/docker-ce.yaml
updatecli/updatecli.d/docker-compose.yml
updatecli/updatecli.d/github-cli.yml
updatecli/updatecli.d/jdk11.yml
updatecli/updatecli.d/jdk17.yml
updatecli/updatecli.d/jdk21.yml
updatecli/updatecli.d/jdk8.yml
updatecli/updatecli.d/nodejs.yml
updatecli/updatecli.d/playwright.yml
updatecli/updatecli.d/python3.yml
updatecli/updatecli.d/trivy.yaml

After PR https://github.com/jenkins-infra/packer-images/pull/852 we need to update all the updatecli manifest to use the new goss file name goss-linux.yaml
(edit by @dduportal)
This PR also introduces:
- Fixes of `updatecli` after #897 
- Track `azcopy` after #898

chore(updatecli) update manifests to also bump versions in the `goss` test harnesses

---

goss/goss-linux.yaml
updatecli/updatecli.d/azcopy.yaml

Fixup of #900
This PR fixes the goss Linux harness to check for the semantic version (x.y.z) instead of the full version (x.y.z-<timestamp>) for `azcopy.
The updatecli manifest is updated to avoid reproducing this error (introduced in #896 when I added the `azcopy` manifest)

chore(goss) fix azcopy version check and updatecli tracking

---

goss/goss-linux.yaml
provisioning/tools-versions.yml
updatecli/updatecli.d/hadolint.yml
updatecli/updatecli.d/jdk11.yml
updatecli/updatecli.d/jq.yml
updatecli/updatecli.d/jx-release-version.yml
updatecli/updatecli.d/launchable.yml
updatecli/updatecli.d/maven.yml
updatecli/updatecli.d/packer.yml
updatecli/updatecli.d/playwright.yml
updatecli/updatecli.d/python3.yml
updatecli/updatecli.d/terraform.yml
updatecli/updatecli.d/updatecli.yml
updatecli/updatecli.d/vagrant.yml

following https://github.com/jenkins-infra/packer-images/pull/906
update the corresponding updatecli manifest to keep the goss file on track.

chore(updatecli): update to keep goss file up2date

---

goss/goss-linux.yaml
updatecli/updatecli.d/git-linux.yml

- Updates the version of git in the Linux Goss test harness (fixup of #893)
- Fixes the `updatecli` manifest to update Git version in the Linux Goss test harness (fixup of #910)

chore(updatecli, tests) fix Linux Git manifest to also update goss

---

goss/goss-linux.yaml
provisioning/tools-versions.yml

Reverts jenkins-infra/packer-images#921
Reverting as the 1.16.1 release doesn't contain any binaries.
- https://github.com/GoogleContainerTools/container-structure-test/releases/tag/v1.16.1
- https://github.com/GoogleContainerTools/container-structure-test/issues/397

Revert "Bump container-structure-test version to 1.16.1"

---

goss/goss-linux.yaml

Fixup of #910 (missing git lfs goss tracking in updatecli) and #944 (git LFS version tracking only updated in the provisioning file)
- This PR fixes the failing build (when git LFS version is checked by goss on Linux)
- The PR #940 ensures this problem won't happen again for Git LFS

hotfix(goss) bump git LFS to 3.4.1

---

goss/goss-linux.yaml
goss/goss-windows.yaml

following #940 the exit-status is required

fixup(goss): putting back exit-status: 0 which is required

---

goss/goss-linux.yaml
goss/goss-windows.yaml
provisioning/tools-versions.yml
updatecli/updatecli.d/yq.yml

Reverts #956 as `yq` version `4.40.5` is not available (yet) in chocolatey packages.
It also fixes the updatecli manifest to check for chocolatey package (to avoid opening a PR if not available yet).

fix(yq) downgrade to 4.25.3

---

sources.pkr.hcl

follow #981 as per https://github.com/jenkins-infra/helpdesk/issues/3823#issuecomment-1887188512

hotfix(docker): add golang to path

---

goss/goss-windows.yaml
provisioning/tools-versions.yml

Reverts jenkins-infra/packer-images#1009
Because:
```
ERROR: could not find version 2.4.1 for vagrant. Output of apt-cache madison is:    
vagrant |    2.4.0-1 | <a href='https://apt.releases.hashicorp.com'>https://apt.releases.hashicorp.com</a> jammy/main amd64 Packages
```
It seems https://github.com/jenkins-infra/packer-images/blob/e32a8483f7d17d60ce070b5fad7dbc5f76d49b90/updatecli/updatecli.d/vagrant.yml#L30-L36 only checks for chocolatey but not for APT packages in `amd64` (`arm64` only uses the "latest") alas)

Revert "Bump vagrant version to 2.4.1"

---

provisioning/ubuntu-provision.sh

This PR adds `dnsutils` to the common requirements installed in order to provide dig(1), used in https://github.com/jenkins-infra/infra-reports/pull/55.

feat(ubuntu): add `dnsutils` to common requirements install

---

provisioning/docker-jenkins-agent.sh

This PR replaces https://github.com/jenkinsci/docker-inbound-agent by https://github.com/jenkinsci/docker-agent.
Follow-up of:
- https://github.com/jenkinsci/docker-agent/pull/570
Ref:
- https://github.com/jenkinsci/docker-agent/issues/569

chore: update `inbound-agent` repo in docker-jenkins-agent.sh

---

provisioning/ubuntu-provision.sh

This PR switches from asdf to GitHub release to retrieve `yq` so we're not blocked by #1042 for https://github.com/jenkins-infra/pipeline-library/pull/834.

chore: install yq from its GitHub repository

---

updatecli/updatecli.d/kubectl.yaml

This PR adds the missing updatecli manifest to keep `kubectl` up to date.
We drifted from https://github.com/jenkins-infra/docker-helmfile/blob/e8d7fc943b557d32352663fb5acd5b2868334396/Dockerfile#L32

chore(updatecli) add a manifest to bump kubectl with pattern

---

build-jenkins-agent-ubuntu.pkr.hcl
goss/goss-common.yaml
provisioning/ubuntu-provision.sh

This PR uses hardcoded path to include asdf in the $PATH so asdf installed tools like yq can be executed.
Note: there might be a way to keep this folder as a variable but as it breaks current uses this "easy" solution should be enough, can be revised in a following pull request.
Ref:
- #1042

fix(ubuntu) correct asdf inclusion in `/etc/environment` for Linux VMs

---

goss/goss-common.yaml
goss/goss-linux.yaml
goss/goss-windows.yaml

This PR uses `asdf list ruby` to retrieve the version installed by asdf and not the vagrant one, cf https://github.com/jenkins-infra/packer-images/pull/1043#pullrequestreview-1878135249
Note: I wasn't sure if goss would have kept the linux version on its config merge if I kept the less precise ruby check in goss-common.yaml, hence the move of the existing one to goss-windows.yaml.
Follow-up of:
- #1043 
Ref:
- #1042

chore: restore ruby version goss check for Linux

---

updatecli/updatecli.d/kubectl.yaml

as per https://github.com/jenkins-infra/helpdesk/issues/3948

chore(updatecli) track kubernetes 1.27.x baseline

---

Jenkinsfile_k8s
Jenkinsfile_updatecli

This PR separates updatecli to its own pipeline, taking in account https://github.com/jenkins-infra/packer-images/pull/606#pullrequestreview-1389903782 and using the new `updatecliAgentLabel` option of the `updatecli` shared pipeline function to use a Docker agent for running updatecli.
Supersedes and closes https://github.com/jenkins-infra/packer-images/pull/606
Follow-up of:
- https://github.com/jenkins-infra/kubernetes-management/pull/3855
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/2778

chore: separate updatecli to its own pipeline

---

provisioning/ubuntu-provision.sh
sources.pkr.hcl

as per https://github.com/jenkins-infra/helpdesk/issues/3823#issuecomment-1918890269
this PR fixes the default ruby version on linux arm64 agents (both VM and container).
we expect ruby 2.6.10 to be the default (only used by puppet) but vagrant ubuntu package on linux arm64 adds ruby 3.0 as explicit dependency. Note that the difference between amd64 and arm64 is due to mismatch version of vagrant: https://github.com/jenkins-infra/packer-images/blob/3a28057d3b4a29c9834d25d9f1ccd9dde82fd8b7/provisioning/ubuntu-provision.sh#L480-L496

fix(ubuntu) prefer `asdf` tools over system tools in default `PATH`es

---

updatecli/updatecli.d/ruby.yml

as per https://github.com/jenkins-infra/helpdesk/issues/3823#issuecomment-1952955515
provide a tracking manifest for ruby, as the versionning is not semver compliant, I choose a trick by using the dockerhub last release until this get a solution https://github.com/updatecli/updatecli/issues/1951

chore(updatecli): add a manifest to track last ruby version

---

build-jenkins-agent-ubuntu.pkr.hcl
provisioning/get-fileshare-signed-url.sh
provisioning/ubuntu-provision.sh

This PR includes the script from the shared pipeline library to generate short-lived SAS token for a File Share with a service principal so it's available for trusted.ci.jenkins.io jobs running on ephemeral agents.
Will be completed in another pull request by an updatecli manifest to keep the script up to date while maintaining the control on when it's updated.
Follow-up of:
- https://github.com/jenkins-infra/jenkins-infra/pull/3323
Ref:
- https://github.com/jenkins-infra/crawler/pull/144#issuecomment-1985450221
- https://github.com/jenkins-infra/helpdesk/issues/3414#issuecomment-1973817455

feat(ubuntu): include `get-fileshare-signed-url.sh` script

---

updatecli/updatecli.d/nodejs.yml

to follow docker-builder image versions : https://github.com/jenkins-infra/docker-builder/commit/db07be9b0c19172f1af9a7f2186e28b5950ec4de

feat(nodejs) Bump updatecli manifest to install new nodejs LTS 20.x.x

---

goss/goss-common.yaml
goss/goss-linux.yaml
goss/goss-windows.yaml
provisioning/tools-versions.yml
provisioning/ubuntu-provision.sh
provisioning/windows-provision.ps1
updatecli/updatecli.d/nodejs-linux.yml
updatecli/updatecli.d/nodejs-windows.yml

as per https://github.com/jenkins-infra/docker-builder/pull/211
we need to upgrade nodejs to 20.12.1 but chocolatey does not provide it.
For now I switch to 2 versions, linux and windows. We will have to choose, if : 
- we remove nodejs from windows if not used
- we change windows nodejs installation to follow the linux versionning
This pull-request once merge will allow updatecli to create a new pull request for linux nodejs

feat(nodejs): split the version between linux and windows

---

goss/goss-windows.yaml

as per https://github.com/jenkins-infra/helpdesk/issues/4090
escape templating to get yaml compliant

chore(goss): correct invalid yaml

---

build-jenkins-agent-ubuntu.pkr.hcl
build-jenkins-agent-windows.pkr.hcl

as per https://github.com/jenkins-infra/helpdesk/issues/4090 resolve `executing "test" at <.Env.AGENT_OS_VERSION>: map has no entry for key "AGENT_OS_VERSION"`

chore(goss): add environement variable to goss execution

---

updatecli/updatecli.d/container-structure-test.yml

following https://github.com/GoogleContainerTools/container-structure-test/issues/445
need to remove temporarily the update for cst

chore(updatecli) remove goss update for cst

---

goss/goss-windows.yaml
provisioning/tools-versions.yml
provisioning/windows-provision.ps1

This PR adds https://github.com/docker/buildx to the Windows images so we can start using it even if we can't build images yet. (For example `docker buildx bake --print` works)
Related:
- https://github.com/jenkinsci/docker-ssh-agent/pull/415/

feat(Windows): add `buildx`

---

updatecli/updatecli.d/kubectl.yaml

As per [#4144](https://github.com/jenkins-infra/helpdesk/issues/4144) this PR updates updatecli manifest to track  1.28.x line of kubectl versions.

chore(updatecli) track 1.28.x line of `kubectl` versions

---

updatecli/updatecli.d/azure-cli.yml

chore(updatecli) fix az CLI manifest to only get the latest GH release

---

updatecli/updatecli.d/datadog-gpg-key.yaml
updatecli/updatecli.d/doctl.yaml

as per https://github.com/jenkins-infra/helpdesk/issues/4178
keep updated the datadog gpg key 
also re-enable updatecli for DOCTL

chore(updatecli): update datadog gpg key and re-enable `doctl` manifest

---

updatecli/updatecli.d/kubectl.yaml

As per https://github.com/jenkins-infra/helpdesk/issues/4161#issuecomment-2299149540
updatecli set to track kub 1.29x versions.

chore(updatecli): Track 1.29x line of kubectl versions

---

updatecli/updatecli.d/maven.yml

As per https://github.com/jenkins-infra/helpdesk/issues/4249#issuecomment-2301857110
We want to make sure there is at least a "real life" smoke test of a new Maven version before rollout.
- We will now rely on the ATH to be up to date which is acceptable
- IF a new Maven version is required, we can always update by hand
cc @MarkEWaite for info

chore(updatecli) use Jenkins ATH as source for maven version

---

provisioning/tools-versions.yml
tests/goss-common.yaml

Reverts jenkins-infra/packer-images#1369
We see `docker login` steps failing: 27.2.1 should fix this (https://github.com/docker/cli/pull/5380) though

Revert "Bump Docker CE version to 27.2.0"

---

provisioning/ubuntu-provision.sh
tests/goss-common.yaml
tests/goss-linux.yaml
tests/goss-windows.yaml

BREAKING CHANGE: removing the default_jdk env variable will introduce failure in goss tess harness for windows and might result in build failures.
As per https://github.com/jenkins-infra/helpdesk/issues/4124#issuecomment-2307122480 :
Any definition of a 'default JDK' and 'update-alternatives' on the jenkins-infra/packer-images has been removed from the ubuntu-provisioning script.  The corresponding goss test patch has also been added to the goss test harness to check installation of maven.

feat!(ubuntu): Removed all definitions of 'default_jdk' from ubuntu image templates

---

provisioning/tools-versions.yml
provisioning/windows-provision.ps1
tests/goss-common.yaml
tests/goss-linux.yaml
tests/goss-windows-2019.yaml
tests/goss-windows.yaml
updatecli/updatecli.d/jdk11.yml

BREAKING CHANGE: removing the default_jdk env variable will introduce failure in goss tess harness.
As per https://github.com/jenkins-infra/helpdesk/issues/4124#issuecomment-2307122480 :
Any definition of a 'default JDK' on the jenkins-infra/packer-images has been removed from the windows-provisioning script. The corresponding goss test patch has also been added to the goss test harness to check installation of maven.

feat!(windows): Removed all definitions of 'default_jdk' from windows image templates

---

updatecli/updatecli.d/maven.yml

As per https://github.com/jenkins-infra/packer-images/issues/1381#issue-2507739764
We switch to the new source of type dockerfile which is easier to read and maintain.
Tested and successful locally.
Also related ( https://github.com/jenkins-infra/helpdesk/issues/4280 )

chore(updatecli):retrieve Maven version from the source with a native resource(dockerfile)

---

provisioning/ubuntu-provision.sh
tests/goss-linux.yaml

As per https://github.com/jenkins-infra/helpdesk/issues/4281#issue-2507657045
Linux VM agents have entropy tools `rngd` and `haveged` installed and enabled at boot time.
Goss text contract to ensure installation of both tools has also been included in this PR.

feat(ubuntu): Introducing entropy tools in ubuntu VM templates

---

provisioning/ubuntu-provision.sh
tests/goss-linux.yaml

As per https://github.com/jenkins-infra/helpdesk/issues/4281#issuecomment-2381344015
This PR removes installation of `haveged` tool on our Linux VM agents since `rngd` produces enough entropy as per our requirements.

feat(ubuntu):Removed haveged installation and goss test

---

Jenkinsfile_updatecli
build-jenkins-agent-windows.pkr.hcl
images-versions.yaml
locals.pkr.hcl
updatecli/updatecli.d/windows-2019-images.yml
updatecli/updatecli.d/windows-2022-images.yml

follow up #1442 to keep track of azure windows images
`az vm image list --location eastus --publisher MicrosoftWindowsServer --offer WindowsServer --sku 2019-datacenter-core-g2 --all --query "[?offer=='WindowsServer'].version" -o tsv | sort -u | tail -n 1`
and
`az vm image list --location eastus --publisher MicrosoftWindowsServer --offer WindowsServer --sku 2022-datacenter-core-g2 --all --query "[?offer=='WindowsServer'].version" -o tsv | sort -u | tail -n 1`
------------------------------------------------------------------------------------------
Those commands need authentication ... sic ...
Converted to draft, until next week, where we will provide the authentication ...
done with https://github.com/jenkins-infra/azure/pull/860
and …

chore(updatecli): add manifest for azure windows images

---

build-jenkins-agent-ubuntu.pkr.hcl
locals.pkr.hcl

As per https://github.com/jenkins-infra/helpdesk/issues/4365#issue-2610776824
and https://github.com/jenkins-infra/packer-images/pull/1443
We want to use the aws `ubuntu` pinned AMI Ids in `image-versions.yaml`, hence the `source_ami` is retrieved from there.

chore(ubuntu): Use pinned aws base AMI IDs from `images-versions.yaml`

---

updatecli/updatecli.d/ubuntu-22-04-amd64-images.yaml
updatecli/updatecli.d/ubuntu-22-04-images.yaml

As per https://github.com/jenkins-infra/helpdesk/issues/4365#issue-2610776824:
As we pinned the base AMI ids for `ubuntu 22.04`, this PR tracks and updates the latest base AMI id of `ubuntu 22.04 AMD64`
Tested locally and successfully:
```
TARGETS
========
updateVersion
-------------
**Dry Run enabled**
✔ - no change detected:
* key "$.aws.ubuntu.'22.04'.amd64" already set to "ami-00eb69d236edcfaf8", from file "./images-versions.yaml"
ACTIONS
========
=============================
SUMMARY:
✔ Bump aws `ubuntu 22.04 AMD64` image version:
Source:
✔ [lastReleaseVersion] Get the latest `ubuntu 22.04 AMD64` AMI ID
Target:
✔ [updateVersion] Update aws `ubuntu 22.04 AMD64` AMI ID in locals
Run Summary
===========
Pipeline(s) run:
* Changed:    0
* Failed:     0
* Skipped:    0
* Succeeded:  1
* …
```

chore(updatecli):Track `ubuntu 22.04 AMD64` AMI ID

---

updatecli/updatecli.d/ubuntu-22-04-arm64-images.yaml

As per https://github.com/jenkins-infra/helpdesk/issues/4365#issue-2610776824:
As we pinned the base AMI ids for ubuntu 22.04, this PR tracks and updates the latest base AMI id of ubuntu 22.04 ARM64
Tested locally and successfully:
```
TARGETS
========
updateVersion
-------------
**Dry Run enabled**
✔ - no change detected:
* key "$.aws.ubuntu.'22.04'.arm64" already set to "ami-039e419d24a37cb82", from file "./images-versions.yaml"
ACTIONS
========
=============================
SUMMARY:
✔ Bump aws `ubuntu 22.04 ARM64` image version:
Source:
✔ [lastReleaseVersion] Get the latest `ubuntu 22.04 ARM64` AMI ID
Target:
✔ [updateVersion] Update aws `ubuntu 22.04 ARM64` AMI ID in locals
Run Summary
===========
Pipeline(s) run:
* Changed:    0
* Failed:     0
* Skipped:    0
* Succeeded:  1
* …
```

chore(updatecli):Track `ubuntu 22.04 ARM64` AMI ID

---

provisioning/tools-versions.yml
tests/goss-linux.yaml
tests/goss-windows.yaml

Reverts jenkins-infra/packer-images#1501
Builds are failing due to this version not available in the ASDF ruby plugin (until https://github.com/asdf-vm/asdf-ruby/pull/419 is merged).

Revert "Bump `ruby` version to 3.3.6"

---

updatecli/updatecli.d/ruby.yml

This PR updates the `updatecli` manifest tracking Ruby version to add a condition checking if the latest found version exists in ASDF.
As seen in #1512 , we had to revert because the "latest" available version of Ruby was not (yet) available in ASDF.
Tested with:
- `3.3.5` as source version: works
- `3.3.6` as source version BEFORE https://github.com/asdf-vm/asdf-ruby/pull/419 was merged (or with an out of date ASDF index): conditions fails, no PR created but `updatecli` process continue working as expected
- `3.3.6` as source AFTER https://github.com/asdf-vm/asdf-ruby/pull/419  was merged: `updatecli` wants to create a new PR
- `3.3.7` (not existing when writing this PR): condition fail as expected

chore(updatecli) when a new Ruby version is available, check for its existence in the ASDF Ruby plugin

---

images-versions.yaml
sources.pkr.hcl
updatecli/updatecli.d/docker-ubuntu-22-04-amd64-images.yml
updatecli/updatecli.d/docker-ubuntu-22-04-arm64-images.yml

As per https://github.com/jenkins-infra/helpdesk/issues/4365#issue-2610776824
This PR pins and track docker image digests for `ubuntu 22_04 AMD64` and `ubuntu 22_04 ARM64`

chore(updatecli):Track docker image digests for `ubuntu 22_04 AMD64` and `ubuntu 22_04 ARM64`

---

Jenkinsfile_k8s

Related to https://github.com/jenkins-infra/helpdesk/issues/4355#issue-2586619289
As per https://github.com/jenkins-infra/packer-images/pull/1526#pullrequestreview-2438017043
This PR removes GC stage from `Jenkinsfile_k8` pipeline to make the garbage collector as a distinct job.

chore(`Jenkinsfile_k8s`) removes GC stage from pipeline

---

Jenkinsfile_gc

Related to https://github.com/jenkins-infra/helpdesk/issues/4355#issue-2586619289
As per https://github.com/jenkins-infra/packer-images/pull/1526#pullrequestreview-2438017043
We add cron trigger expression to the pipeline to execute only once daily.

feat(Jenkinsfile_gc) adds cron trigger expression

---

Jenkinsfile_gc

Related to https://github.com/jenkins-infra/helpdesk/issues/4355#issue-2586619289
Since we don't use a docker agent, the agent label has been updated to a suitable agent for the `Jenkinsfile_gc` pipeline.

chore(`Jenkinsfile_gc`) updates the agent used to `jnlp-linux-arm64`

---

provisioning/tools-versions.yml
tests/goss-common.yaml

Reverts jenkins-infra/packer-images#1529 because https://github.com/jenkins-x-plugins/jx-release-version/issues/123

Revert "Bump jx-release-version version to 2.7.7"

---

sources.pkr.hcl

Related to https://github.com/jenkins-infra/helpdesk/issues/4355
As per https://github.com/jenkins-infra/helpdesk/issues/4355#issuecomment-2493454384
We add a `Name` tag with a value matching the GC filter to ensure all the dangling instances created by `packer-images` are terminated

chore(`packer-images`) adds `Name` tag with a value matching the GC filter

---

build-jenkins-agent-ubuntu.pkr.hcl
updatecli/updatecli.d/az-ubuntu-22-04-amd64-images.yml

As per https://github.com/jenkins-infra/helpdesk/issues/4365#issue-2610776824
This PR pins and tracks the latest AZ image for `ubuntu 22_04 AMD64`

chore(updatecli):Track `ubuntu 22_04 AMD64` AZ images

---

cleanup/aws_snapshots.sh

Related to https://github.com/jenkins-infra/helpdesk/issues/4355
As per https://github.com/jenkins-infra/helpdesk/issues/4355#issuecomment-2493441945
This PR enables debugging to skip snapshots in use

feat(aws garbage collector) skips snapshots in use

---

cleanup/azure.sh

ref: https://github.com/jenkins-infra/helpdesk/issues/4445
a `az resource show` show that the field existing is `createdTime` but not timeCreated, but I cannot find trace of that change on azure
```
{
"changedTime": "2024-12-11T14:24:00.478990+00:00",
"createdTime": "2024-12-11T14:24:00.452248+00:00",
"extendedLocation": null,
"id": "/subscriptions/<redacted>/resourceGroups/DEV-PACKER-BUILDS/providers/Microsoft.Compute/disks/pkrosmq3gtdonba",
"identity": null,
"kind": null,
"location": "eastus2",
"managedBy": "/subscriptions/<redacted>/resourceGroups/dev-packer-builds/providers/Microsoft.Compute/virtualMachines/pkrvmmq3gtdonba",
"name": "pkrosmq3gtdonba",
"plan": null,
"properties": null,
"provisioningState": "Succeeded",
"resourceGroup": "DEV-PACKER-BUILDS",
"sku": {
"capacity": null, …
```

chore(GC/azure): fix Azure VM deletion by changing timeCreated to createdTime

---

sources.pkr.hcl

- It's faster than `gp2` as per https://docs.aws.amazon.com/ebs/latest/userguide/ebs-volume-types.html
- Looks like the current ec2 plugin support gp3 now: https://issues.jenkins.io/browse/JENKINS-73660

feat(aws) use `gp3` EBS volume

---

provisioning/ubuntu-provision.sh
provisioning/windows-provision.ps1

Same as https://github.com/jenkins-infra/github-reusable-workflows/pull/41 + https://github.com/jenkins-infra/github-reusable-workflows/issues/39
We want to avoid the [Tragedy of Common Goods](https://en.wikipedia.org/wiki/Tragedy_of_the_commons) and as such we should only download binaries from the recommended sources.
In the case of Maven, using the Apache CDN instead of archives is the least we can do to decrease our hammering of the Apache public INFRA, and also to decrease chances of failing builds for us.
Note: https://github.com/jenkins-infra/github-reusable-workflows/issues/39#issuecomment-2439796240 shows that there might be "different/better" sources. Worth discussing and changing again, but this PR is a first step.

fix(ubuntu/windows) avoid tragedy of commons goods: use `dlcdn` apache download server for Maven

---

build-jenkins-agent-windows.pkr.hcl
tests/goss-common.yaml
tests/goss-linux.yaml
tests/goss-windows.yaml

following https://github.com/jenkins-infra/packer-images/pull/1585 we discovered a long time to check hadolint on windows, this timeout should avoid wrong failure for goss.
also reduce max-concurrent to 1 for windows to avoid mistakes on windows goss

chore(tests): move hadolint to goss-common and add specific timeout

---

provisioning/ubuntu-provision.sh

As per https://matrix.to/#/!JLUOInpEYmxJIYXlzs:matrix.org/$Nxb90lxEWhAPD430U6VMX0w1nX3NytYbmIwPm2IkO1c?via=g4v.dev&via=gitter.im&via=matrix.org by @timja:
> GOPATH isn't writeable by the user
The `go` installation does report a `GOPATH` set to `/home/jenkins/go` but this directory does not exist by default.
This PR ensures it is created with the proper permissions
Ref. https://go.dev/wiki/GOPATH

fix(ubuntu) ensure golang installation works with the default `jenkins` user `GOPATH`

---

provisioning/windows-provision.ps1

Related to https://github.com/jenkins-infra/helpdesk/issues/3865
This PR applies @jtnord's proposal in https://github.com/jenkins-infra/pipeline-library/pull/899#discussion_r1910892747 to set up tje default autoCRLF for Git.
Note: it was explicitly set to `false` since 5 years (https://github.com/jenkins-infra/packer-images/pull/8). Not sure why, so let's go with the new setting to fix spotless issues *also* in the Windows VM templates

fix(windows) ensure Git has autoCRLF enabled

---

tests/goss-common.yaml
updatecli/updatecli.d/docker-compose.yml

Tests are failing due to https://github.com/docker/compose/issues/12459
Let's comment out and roll

tests: bypass Docker Compose version check

---

build-jenkins-agent-ubuntu.pkr.hcl
build-jenkins-agent-windows.pkr.hcl
locals.pkr.hcl
sources.pkr.hcl
variables.pkr.hcl

Related to https://github.com/jenkins-infra/helpdesk/issues/4316
This PR enables [EC2 Fast Launch](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/win-ami-config-fast-launch.html) for the EC2 Windows templates.
The goal is to ensure faster boot of Windows VM agents

feat(windows/ec2) enable Fast Launch with default setup

---

build-jenkins-agent-windows.pkr.hcl

revert https://github.com/jenkins-infra/packer-images/pull/1609
but with `--max-concurrent=1` to try to avoid timeout on goss test for windows probably due to the go code on windows not handling correctly go routines.

chore(goss/windows): adding back a retry timeout only for windows goss

---

sources.pkr.hcl

to avoid creating AMI or Azure IMAGE if not on production, will save time on PR checks

chore(publish): skip image/ami creation if not on production

---

images-versions.yaml

Reverts jenkins-infra/packer-images#1697
Testing if reverting helps fixing https://github.com/jenkins-infra/packer-images/pull/1702

Revert "Bump aws `windows 2019 AMD64` AMI ID"

---

build-jenkins-agent-windows.pkr.hcl

Since a few days, we start seeing Windows 2019 provisioning failures on AWS (not sure when did it start and it is correlated to a base image change).
The error is the following:
```
amazon-ebs.windows: & : The term 'C:/Program Files/Amazon/EC2Launch/ec2launch' is not recognized as the name of a cmdlet, function, script[0m
amazon-ebs.windows: file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct[0m
amazon-ebs.windows: and try again.[0m
amazon-ebs.windows: At C:\Windows\Temp\script-679a67f3-a287-b936-7f69-b05522aa0c7e.ps1:1 char:3[0m
amazon-ebs.windows: + & 'C:/Program Files/Amazon/EC2Launch/ec2launch' reset --block[0m
amazon-ebs.windows: +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
amazon-ebs.windows:     + …
```

fix(windows/AWS) correct path to the `EC2Launch.exe` command

---

build-jenkins-agent-windows.pkr.hcl

as per https://github.com/jenkins-infra/packer-images/issues/1731#event-16276289702
re-enabling windows test with goss

Revert "chore(goss/windows): temporarily remove the goss tests for windows"

---

updatecli/updatecli.d/windows-2019-aws-images.yaml

as per https://github.com/jenkins-infra/helpdesk/issues/4565
the fast launch failed because of the sysprep step failing.
Those AMI got the correct command pre-installed.

chore(updatecli): change ami line for AWS windows 2019 to hove EC2 Launch V2 pre-installed

---

provisioning/windows-provision.ps1

set the default encoding to utf-8
need to be check in real life within an AMI, so lets merge and checked the published AMI
⚠️ WARNING don't create a tag while not sure it worked

fix(windows): set the default encoding to utf-8

---

provisioning/windows-provision.ps1

Ref. https://github.com/jenkins-infra/helpdesk/issues/4574
Twin of https://github.com/jenkins-infra/pipeline-library/pull/914

fix(Windows/git) Ensure Git LongPath is set at system level

---

provisioning/tools-versions.yml

as per https://github.com/jenkins-infra/helpdesk/issues/4574\#issuecomment-2703350642
reverting git on windows to 2.47.1

revert[git/windows] revert version from 2.48.1 to 2.47.1

---

updatecli/updatecli.d/kubectl.yaml

Ref. https://github.com/jenkins-infra/helpdesk/issues/4546

chore(updatecli) track kubectl `1.31.x` line instead of `1.30.x`

---

.github/workflows/release-drafter.yml

Ref. https://github.com/jenkins-infra/helpdesk/issues/2982

chore(GHA) use Ubuntu latest runners on Release Drafter

---

updatecli/updatecli.d/golangci-lint.yml

Ref. https://github.com/jenkins-infra/docker-openvpn/pull/413#issuecomment-2873407919
We weren't tracking this CLI version and there is a major version upgrade to perform.

chore(updatecli) track version of `golangci-lint`

---

provisioning/ubuntu-provision.sh
updatecli/updatecli.d/azcopy.yaml

Since 48h, the installation of `azcopy` fails with the following error:
```bash
$ apt-get install --yes --no-install-recommends azcopy=10.29.0
Reading package lists...
azure-arm.ubuntu: Building dependency tree...
Reading state information...
Package azcopy is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or is only available from another source
E: Version '10.29.0' for 'azcopy' was not found
```
The package 10.29.0 is not available anymore in the repository. It worked the day before but not anymore.
This PR is a fix which uses the debian packages from the AzCopy GitHub releases (which we use as source for the updatecli version tracking) which are available for both x86_64 and arm64.
We loose the checksum check of the …

fix(ubuntu) use `azcopy` debian package from GH release to circumvent Microsoft Azcopy package errors

---

provisioning/windows-provision.ps1

Adding the Server-Media-Foundation functionality to remove warnings from the playwright testing framework
See https://github.com/jenkinsci/pipeline-graph-view-plugin/pull/761#issuecomment-2883249548

Add Server-Media-Foundation as part of the Windows provisioning script

---

jdks-infos.yaml
tests/goss-linux.yaml
tests/goss-windows.yaml
updatecli/values.yaml

as per https://github.com/jenkins-infra/helpdesk/issues/4641
introducing jdk25 in agents templates

feat: add JDK25 version `25+26-EA`

---

tests/goss-linux.yaml
tests/goss-windows.yaml
updatecli/updatecli.d/jdks.yml
updatecli/values.yaml

as per https://github.com/jenkins-infra/packer-images/pull/1998#discussion_r2139639182
moving the updatecli manifest change to this PR
⚠️ need https://github.com/jenkins-infra/packer-images/pull/1998 to be merged and then rebase this one before merging

chore(updatecli): track the jdk25 version

---

updatecli/values.yaml

as per https://github.com/jenkins-infra/helpdesk/issues/4707
wait for #2012 to check if the dependon work as expected

chore(updatecli): temporarily remove jdk25 tracking

---

updatecli/values.yaml

Reverts jenkins-infra/packer-images#2013
following https://github.com/adoptium/api.adoptium.net/issues/1523#issuecomment-2983064226

Revert "chore(updatecli): temporarily remove jdk25 tracking"

---

provisioning/ubuntu-provision.sh
provisioning/windows-provision.ps1

Note: I did a "fallback" technique on Linux (try normal download otherwise fallback to archives) and tested it locally.
For Windows I've been lazy and provided a quick fix: always use the archives system.

fix(linux/windows) Ensure Maven archive is always downloaded when a new version is available while we use an older one

---

updatecli/updatecli.d/kubectl.yaml

We're going to upgrade Kubernetes to 1.32 and a new `publick8s` cluster is gonna be created directly in 1.32.
As such, let's move the Kubernetes client to 1.32. It will keep compatibility with 1.31.x servers.

chore(updatecli/kubectl) bump line from `1.31.x` to `1.32.x`
